// <auto-generated />
using IT3045C_Final_Project.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IT3045C_Final_Project.Migrations
{
    [DbContext(typeof(FavoriteFoodsContext))]
    partial class FavoriteFoodsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IT3045C_Final_Project.Models.FavoriteFoods", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FavBreakfast")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FavDinner")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FavLunch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FavSnack")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FavoriteFoods");

                    b.HasData(
                        new
                        {
                            Id = 14969824,
                            FavBreakfast = "Waffles",
                            FavDinner = "Pasta",
                            FavLunch = "PBJ",
                            FavSnack = "Apple slices"
                        },
                        new
                        {
                            Id = 12345678,
                            FavBreakfast = "Toast",
                            FavDinner = "Hamburgers",
                            FavLunch = "BLT",
                            FavSnack = "Chips"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
