// <auto-generated />
using System;
using IT3045C_Final_Project.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IT3045C_Final_Project.Migrations.TVShows
{
    [DbContext(typeof(TVShowsContext))]
    [Migration("20240802193507_TVShowsMigration")]
    partial class TVShowsMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IT3045C_Final_Project.Models.TVShow", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumSeasons")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<string>("ShowName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("TVShows");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Genre = "Drama",
                            NumSeasons = 4,
                            ReleaseDate = new DateOnly(2018, 6, 3),
                            ShowName = "Succession"
                        },
                        new
                        {
                            ID = 2,
                            Genre = "Crime",
                            NumSeasons = 4,
                            ReleaseDate = new DateOnly(2015, 6, 24),
                            ShowName = "Mr. Robot"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
