// <auto-generated />
using System;
using IT3045C_Final_Project.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IT3045C_Final_Project.Migrations
{
    [DbContext(typeof(CourseEnrollmentsContext))]
    partial class CourseEnrollmentsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IT3045C_Final_Project.CourseEnrollment", b =>
                {
                    b.Property<int?>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("StudentID"));

                    b.Property<string>("CourseName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourseNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CreditHours")
                        .HasColumnType("int");

                    b.Property<string>("Track")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentID");

                    b.ToTable("CourseEnrollments");

                    b.HasData(
                        new
                        {
                            StudentID = 14981719,
                            CourseName = "Contemporary Programming",
                            CourseNumber = "IT3045C",
                            CreditHours = 3,
                            Track = "Software Application Development"
                        },
                        new
                        {
                            StudentID = 14981720,
                            CourseName = "Network Security",
                            CourseNumber = "IT3071C",
                            CreditHours = 3,
                            Track = "Cybersecurity"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
