// <auto-generated />
using System;
using IT3045C_Final_Project.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IT3045C_Final_Project.Migrations.FavoriteTVShows
{
    [DbContext(typeof(FavoriteTVShowsContext))]
    [Migration("20240731003017_FavoriteTVShowsMigration")]
    partial class FavoriteTVShowsMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IT3045C_Final_Project.Models.FavoriteTVShow", b =>
                {
                    b.Property<int?>("StudentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("StudentID"));

                    b.Property<string>("Genre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumSeasons")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<string>("ShowName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentID");

                    b.ToTable("FavoriteTVShows");

                    b.HasData(
                        new
                        {
                            StudentID = 14981719,
                            Genre = "Drama",
                            NumSeasons = 4,
                            ReleaseDate = new DateOnly(2018, 6, 3),
                            ShowName = "Succession"
                        },
                        new
                        {
                            StudentID = 14981720,
                            Genre = "Crime",
                            NumSeasons = 4,
                            ReleaseDate = new DateOnly(2015, 6, 24),
                            ShowName = "Mr. Robot"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
